name: Publish to JFrog Artifactory

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI-CD-using-GitOps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn clean install
      working-directory: /home/runner/work/Telus-Project-GitOps/Telus-Project-GitOps

    - name: JUnit Tests
      run: mvn test
      working-directory: /home/runner/work/Telus-Project-GitOps/Telus-Project-GitOps
      
    - name: 'Code Analysis with Checkstyle'
      run: mvn checkstyle:checkstyle

    - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Analyze using Sonar Cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=sasidharsunny_Telus-App-GitOps






      

    - name: Upload artifact 
      uses: actions/upload-artifact@master
      with:
          name: artifacts
          path: /home/runner/.m2/repository/com/example/maven-project/webapp/1.0-SNAPSHOT/webapp-1.0-SNAPSHOT.war

  
