name: Publish to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  CI-CD-using-GitOps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn clean install
      working-directory: /home/runner/work/Telus-Project-GitOps/Telus-Project-GitOps

    - name: JUnit Tests
      run: mvn test
      working-directory: /home/runner/work/Telus-Project-GitOps/Telus-Project-GitOps
      
    - name: 'CODE ANALYSIS WITH CHECKSTYLE'
      run: mvn checkstyle:checkstyle
  
